name: pre-commit

on: [push]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      # POETRY:START #
      # This installs poetry using pip instead of the poetry recommended install script for two reasons:
      # 1. It's cross platform
      # 2. The normal installation wasn't registering the `poetry` executable in the shell in later commands (for reasons unknown)
      # 3. This repo's pre-commit config expects poetry to be available as "python -m poetry"
      - name: Install poetry
        run: python -m pip install --upgrade pip poetry
      # Install Poetry dependencies (based on https://github.com/psf/black/actions/runs/816321/workflow)
      - name: Get poetry cache directory path
        id: poetry-cache-dir-path
        run: echo "::set-output name=dir::$(poetry config cache-dir)"
      - uses: actions/cache@v2
        id: poetry-cache # use this to check for `cache-hit` (`steps.poetry-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.poetry-cache-dir-path.outputs.dir }}
          key: poetry-${{ hashFiles('**/poetry.lock') }}-${{ runner.os }}-${{ matrix.python-version }}
      - name: Install Poetry dependencies
        run: poetry install
      # POETRY:END #
      - uses: pre-commit/action@v2.0.0
